workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Stripe API:
        inputs:
            - location: ../minimal-openapi.json
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/daves/daves/stripe-api
targets:
    stripe:
        target: mcp-typescript
        source: Stripe API
